content_folder = ['art', 'blog', 'journal']
relative_build_url = "/"
absolute_build_url = "https://randomtwins.github.io/Chisai/"
build_folder = "build/"
assets_folder = "assets/"
medias_folder = "medias/"
template_file = "partials/main.html"
template_nav = "partials/nav.html"
rss_template = "partials/rss.xml"
rss_item_template = "partials/item.xml"
name_of_site = "Rien de très important"
site_meta_description = "Collection de choses et d'autres."
twitter_name = "@randotwino"
home_name = "Home"
see_all = "Voir +"
go_back = "Retour vers"
date_format = "ISO"  # Choose between EU day-month-year or ISO year-mont-day
flat_build = True # True or False, if True, all files will be written in the root of the website
